name: Deploy Flutter Web App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3' # 사용하는 Flutter 버전으로 변경

    - name: Install Dependencies
      run: flutter pub get

    - name: Build Web
      run: flutter build web --release

    - name: Add .jindolma
      run: echo > build/web/.jindolma

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.key }} # repository에서 사용할 시크릿 키 이름
        publish_dir: build/web
        publish_branch: gh-pages